from nipype.interfaces.base import File, traits
from nipype.interfaces import ants

class ANTSInputSpecRPT(ants.ANTSInputSpec):
    generate_report = traits.Bool(
        desc="Set to true to enable report generation for node"
    )

class ANTSOutputSpecRPT(ants.ANTSOutputSpec):
    html_report = File(desc="Filename of report generated by node")

class ANTSRPT(ants.ANTS):

    input_spec = ANTSInputSpecRPT
    output_spec = ANTSOutputSpecRPT

    def _generate_report(self):
        raise NotImplementedError
